### check coordinates false
GET http://localhost:3000/game?pic_name=board1&char_name=waldo&x=1200&y=900

### check coordin. true
GET http://localhost:3000/game?pic_name=board1&char_name=waldo&x=1530&y=700

### board 2 coor false
GET http://localhost:3000/game?pic_name=board2&char_name=waldo&x=1200&y=900

### board 2 coor true
GET http://localhost:3000/game?pic_name=board2&char_name=wizard&x=810&y=1010

### board 3 false
GET http://localhost:3000/game?pic_name=board3&char_name=waldo&x=1200&y=900

### board 3 true
GET http://localhost:3000/game?pic_name=board3&char_name=wenda&x=1210&y=310


### start time

GET http://localhost:3000/game/start?id=12345

### end time

GET http://localhost:3000/game/end?id=12345

### new high score 

GET http://localhost:3000/game/score?id=12345&name=eric

### new high score post
POST http://localhost:3000/game/score
Content-Type: application/json

{"name": "craig",
"id":"12345"
}

### get high score

GET http://localhost:3000/game/highscore

### delete current high scores
GET http://localhost:3000/game/deletecurrent
