### check coordinates false
GET http://localhost:3000/game?char_name=waldo&x=1200&y=900

### check coordin. true
GET http://localhost:3000/game?char_name=waldo&x=1220&y=774

### start time

GET http://localhost:3000/game/start?id=12345

### end time

GET http://localhost:3000/game/end?id=12345

### new high score 

GET http://localhost:3000/game/score?id=12345&name=eric

### new high score post
POST http://localhost:3000/game/score
Content-Type: application/json

{"name": "craig",
"id":"12345"
}